---
deployment:
  tasks:
    - export APPPATH=/home/failler/faiillery.my.id/faillery
    - export PUBLICPATH=/home/failler/faiillery.my.id/public

    - /bin/find $APPPATH/public -mindepth 1 ! -name "index.php" -exec /bin/cp -a {} $PUBLICPATH/ \;
    - /bin/cp -f $APPPATH/public/.htaccess $PUBLICPATH/.htaccess