---
deployment:
  tasks:
    # - export DEPLOYPATH=../public/
    # - /bin/mkdir -p $DEPLOYPATH

    - export DEPLOYPATH=/home/faiiller/faiillery.my.id/public/
    - export REPOPATH=/home/faiiller/faiillery.my.id/faiillery-repo/
    - /bin/mkdir -p $DEPLOYPATH

    - /bin/find public -maxdepth 1 -mindepth 1 ! -name "index.php" -exec /bin/cp -a {} $DEPLOYPATH \;
    - /bin/cp -f public/.htaccess $DEPLOYPATH.htaccess


